# Generated by Django 2.2 on 2020-08-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='accounts',
        ),
    ]
