# Generated by Django 3.0.8 on 2020-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200816_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='상품이름')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('want', models.CharField(max_length=32, verbose_name='원하는물건')),
                ('postalcode', models.IntegerField(null=True, verbose_name='우편번호')),
                ('juso1', models.TextField(null=True, verbose_name='주소지')),
                ('juso2', models.TextField(null=True, verbose_name='상세주소')),
                ('tradedetail', models.TextField(null=True, verbose_name='교환방법')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'baton_Product',
            },
        ),
    ]
